# Generated by Django 3.0.5 on 2020-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='core.Post'),
        ),
    ]
