# Generated by Django 3.0.5 on 2020-10-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
