# Generated by Django 3.0.5 on 2020-10-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201006_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'permissions': (('create_column', 'Create Column'), ('writer', 'Create Post'), ('moderator', 'Approve Post'))},
        ),
    ]
