# Generated by Django 3.0.5 on 2020-10-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201011_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprroved',
            field=models.CharField(choices=[('A', 'Approve Post'), ('W', 'Waiting'), ('R', 'Reject Post')], default='W', max_length=1),
        ),
    ]
