# Generated by Django 3.0.5 on 2020-10-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_aprroved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aprroved',
            new_name='approved',
        ),
    ]
